# Full configuration reference: https://symfony.com/bundles/ux-icons/current/index.html#configuration
ux_icons:

    # Default HTML attributes to add to all icons
    default_icon_attributes:

        # Use current text color to fill the icon
        fill: currentColor

        # Default dimensions
        height: '1em'
        width: '1em'

    # on plane
    ignore_not_found: true
    iconify:
        enabled: false
        on_demand: false

when@prod:
    ux_icons:
        # Suppress exceptions for missing icons in production
        ignore_not_found: true
